#+title: Readme
#+author: Kopnov Alexandr
#+date: 2023-07-09

* About

Greg tech production lines are difficult to remember in their entirety, so I
prefer to have a flowchart. It came to making graphs using =graphviz=, which can
look good, but resulting labels are... verbose. This script converts =json=
containing production line description into graphviz =.dot= file (and calls ~dot~ on
it to transform to png).

* Input spec
Production line is almost recursively defined (but currently not recursively
processed).

Each cluster has following fields:
+ name (ignored for top level)
+ buffers:
  + input
  + output
  + other
+ recipes (optional for top level)

Production line (top level cluster) additionaly has fields
+ materials:
  - solids
  - fluids
+ clusters

Parameters of recipe is:
+ machine
+ tier --- voltage tier
+ duration (in seconds)
+ inputs
+ outputs

As an example, [[platline.json]] is provided.

* Theming

At this moment in time, graphs are primarily black and white, other than inputs
and outputs being colored to make them stand out, but I'm open to suggestions
for better coloring.
